{
 "title": "Elasticsearch - Cluster",
 "description": "Graphs at the elasticsearch cluster level",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(elasticsearch_indices_docs{job=\"elasticsearch-exporter\"}, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "number_of_nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{job=\"elasticsearch-exporter\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  data_nodes"
    },
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{job=\"elasticsearch-exporter\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  nodes (total)"
    }
   ]
  },
  {
   "title": "health_number_of",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_in_flight_fetch{job=\"elasticsearch-exporter\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  in_flight_fetch"
    },
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{job=\"elasticsearch-exporter\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  pending_tasks"
    },
    {
     "expr": "elasticsearch_cluster_health_timed_out{job=\"elasticsearch-exporter\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  timed_out"
    }
   ]
  },
  {
   "title": "active_primary_shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{job=\"elasticsearch-exporter\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "active_shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{job=\"elasticsearch-exporter\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  active (total)"
    }
   ]
  },
  {
   "title": "delayed_unassigned_shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{job=\"elasticsearch-exporter\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  delayed_unassigned"
    }
   ]
  },
  {
   "title": "initializing_shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{job=\"elasticsearch-exporter\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  initializing"
    }
   ]
  },
  {
   "title": "relocating_shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{job=\"elasticsearch-exporter\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  relocating"
    }
   ]
  },
  {
   "title": "unassigned_shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{job=\"elasticsearch-exporter\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}