{
 "title": "Aggregated master metrics",
 "description": "Dashboard to get an overview of one server",
 "tags": [
  "oxalide",
  "infra"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(kube_node_labels{label_kubernetes_io_role=\"master\"},node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Out of space",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_out_of_disk{node=~\"$node\", condition=\"true\"})"
    }
   ]
  },
  {
   "title": "CPU Request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})",
     "legendFormat": "# of CPUs"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"})",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})",
     "legendFormat": "# of Memory"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\"}) - sum(node_filesystem_free{device!=\"rootfs\"})) / sum(node_filesystem_size{device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu[2m])) by (mode) * 100",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)) / sum(node_memory_MemTotal)) * 100"
    }
   ]
  }
 ]
}