{
 "title": "Node metrics",
 "description": "Dashboard to get an overview of one server",
 "tags": [
  "oxalide",
  "infra"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(node_boot_time, instance)"
   },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "namespace", "query": "namespaces()" },
   { "name": "metric", "query": "metrics($namespace)" },
   { "name": "dimension", "label": "Dimenson key", "query": "dimension_keys($namespace)" },
   {
    "name": "AutoScalingGroupName",
    "query": "dimension_values($region, $namespace, $metric, $dimension)"
   },
   {
    "name": "Instance",
    "query": "ec2_instance_attribute($region, PrivateIpAddress, { \"tag:aws:autoscaling:groupName\": [ \"$AutoScalingGroupName\" ] })"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu{instance=~\"$Instance:.+\"}[2m])) by (mode) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$Instance:.+\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$Instance:.+\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$Instance:.+\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$Instance:.+\"} - node_memory_MemFree{instance=~\"$Instance:.+\"} - node_memory_Buffers{instance=~\"$Instance:.+\"} - node_memory_Cached{instance=~\"$Instance:.+\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers{instance=~\"$Instance:.+\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached{instance=~\"$Instance:.+\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree{instance=~\"$Instance:.+\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((node_memory_MemTotal{instance=\"$server\"} - node_memory_MemFree{instance=\"$server\"}  - node_memory_Buffers{instance=\"$server\"} - node_memory_Cached{instance=\"$server\"}) / node_memory_MemTotal{instance=\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_read{instance=~\"$Instance:.+\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_written{instance=~\"$Instance:.+\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_ms{instance=~\"$Instance:.+\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\",instance=\"$server\"}) - sum(node_filesystem_free{device!=\"rootfs\",instance=\"$server\"})) / sum(node_filesystem_size{device!=\"rootfs\",instance=\"$server\"})"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{instance=~\"$Instance:.+\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes{instance=~\"$Instance:.+\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "sum(kube_node_status_ready)", "legendFormat": "Nb nodes" }
   ]
  }
 ]
}